language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION="1.4"
  - DJANGO_VERSION="1.5"
  - DJANGO_VERSION="1.6"
  - DJANGO_VERSION="1.7"
  - DJANGO_VERSION="1.8"

install:
  - pip install -r devrequirements_${DJANGO_VERSION}.txt

script: python runtests.py

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="1.3"
    - python: "3.4"
      env: DJANGO_VERSION="1.3"
    - python: "3.3"
      env: DJANGO_VERSION="1.4"
    - python: "3.4"
      env: DJANGO_VERSION="1.4"
